import Head from "next/head";
import Layout from "../../components/layout";

export default function SignIn() {
  return (
    <div className="bg-black">
      <Head>
        <title>Playnetz || SignIn</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen min-h-screen p-4 w-full"></main>
    </div>
  );
}
