import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Button } from "../../components/button/button";
import CustomInput from "../../components/customInput/customInput";
import PlaynetzLogo from "../../components/logo/logo";
import Producer from "../../assets/producer.svg";
import User from "../../assets/user.svg";
import { StyledBackButton } from "../../styles/theme.js/theme";
import { BackIcon } from "../../components/icons/backIcon";
import { useRouter } from "next/router";

export default function SignUp() {
  const router = useRouter();

  return (
    <div className="bg-[#050F14]">
      <Head>
        <title>Playnetz || SignUp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen min-h-screen w-full">
        <div className="w-full h-full">
          <div className="w-full absolute top-0 left-0 p-6">
            <StyledBackButton onClick={() => router.push("/")}>
              <BackIcon />
              back
            </StyledBackButton>
          </div>
          <div className="w-full h-full grid grid-cols-3 ">
            <div className="hidden md:flex bg-[#33a4d8] md:col-span-2 h-full w-full justify-center"></div>
            <div className="col-span-3 md:col-span-1 flex items-center justify-center w-full h-full p-4">
              <div className="w-full p-6">
                <div className="flex flex-col gap-4">
                  <p className="text-white text-sm">Simple. Secure. Fun.</p>
                  <div className="flex gap-2 flex-col mb-4">
                    <h2 className="text-white text-3xl lg:text-5xl font-bold w-full">
                      Getting Ready! <br />
                      <span className="">Joining Planetz is easy.</span>
                    </h2>
                    <p className="text-white mt-4 text-sm">
                      (signing up only takes 3 minutes!)
                    </p>
                  </div>
                  <div className="flex flex-col gap-4">
                    <h2 className="text-white text-2xl font-semibold">
                      Select user type to begin
                    </h2>
                    <div className="flex w-full items-center justify-center self-center gap-4">
                      <Button className="w-1/2">Producer</Button>
                      <Button className="w-1/2">User</Button>
                    </div>
                    <div className="mt-4 flex items-center gap-x-2">
                      <p className="text-white">already have an account?</p>
                      <Link href="/auth/signIn" passHref>
                        <a className="text-[#33A4D8] focus:underline text-lg font-semibold">Sign In</a>
                      </Link>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
