import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-green-400 w-screen h-screen">
        <div>
          <h2 className='animate-pulse'>playnetz_frontend</h2>
        </div>
      </main>
    </div>
  )
}
