import Head from "next/head";
import Layout from "../components/layout";
import { StyledSearchButton as StyledSubscribeButton } from "../styles/theme.js/theme";
import CustomInput from "../components/customInput/customInput";
import { useEffect, useRef } from "react";

export default function Home() {
  const inputRef = useRef(null);

  useEffect(() => {
    if (inputRef.current) {
      inputRef.current.focus()
    }
  }, []);

  return (
    <div className="homeBackground">
      <Head>
        <title>Playnetz || Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div className="flex flex-col w-full max-w-[1440px] h-full">
          <div className="flex flex-col items-center">
            <div className="flex flex-col w-full lg:w-[65%] h-[35rem] gap-6 justify-center items-center ">
              <h2 className="text-5xl font-bold text-center w-full max-w-[34.5rem]">
                Entertainment is fun Get your 2nd month free
              </h2>
              <form className="w-full md:w-[65%] lg:w-[70%]">
                <div className="grid grid-cols-3 items-stretch">
                  <CustomInput
                    className="bg-white w-full col-span-2 placeholder-black text-black font-light tracking-normal"
                    placeholder="Enter Your Email"
                    type="email"
                    refs={inputRef}
                  />
                  <StyledSubscribeButton className={"-ml-5 w-full"}>
                    Let’s Have Fun
                  </StyledSubscribeButton>
                </div>
              </form>
              <div>
                <p className="text-center">Stream anywhere. Abort anytime</p>
              </div>
            </div>
            <div className="bottom-0 mb-4 p-4">
              <p className="text-center">
                Ready to Stream? Or Be the producer. Enter your email to reclaim
                your membership
              </p>
            </div>
          </div>
        </div>
      </Layout>
    </div>
  );
}
